config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  resources :users, :menu_categories, :menu_items, :carts, :cart_items, :orders, :order_items, :addresses
  get "/user/menu/:id" => "customers#index", as: :users_menu
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/update_menucategory_view/:id" => "menu_categories#update_view", as: :update_category_view
  get "/add_item_view/:id" => "menu_categories#add_item_view", as: :add_item_view
  get "/menuitem_view/:id" => "menu_items#render_items", as: :menu_items_view
  get "/update_menuitem_view/:id" => "menu_items#update_view", as: :update_item_view
  post "/create_menu_category" => "menu_categories#create_category", as: :create_menu_category
  put "/add_quantity/:id" => "cart_items#add_quantity", as: :add_quantity
  put "/reduct_quantity/:id" => "cart_items#reduct_quantity", as: :reduct_quantity
  delete "/delete_all_items" => "cart_items#delete_all", as: :destroy_all_items
  get "/checkout" => "cart_items#checkout", as: :checkout
  put "/update_use_address" => "addresses#update_use_address", as: :update_use_address
  post "/orders" => "orders#create", as: :create_orders
  get "/update_address_view/:id" => "addresses#update_address_view", as: :update_address_view
  get "/customer_orders" => "orders#customer_orders", as: :customer_orders
  put "/cancel_order/:id" => "orders#cancel_order", as: :cancel_order
  put "/update_pending_order" => "orders#update_pending_order", as: :mark_as_delivered
  get "/admin" => "admin#index", as: :admin_index
  get "/reports" => "admin#reports", as: :reports
  get "/users_profile" => "admin#users_profile", as: :users_profile
  get "/update_special_users_view" => "admin#update_special_users_view", as: :update_special_users_view
  patch "/edit_special_users" => "admin#edit_special_users", as: :edit_special_users
  get "/invoices" => "admin#invoices", as: :invoices
  get "/customers_profile_view" => "admin#customers_profile_view", as: :customers_profile_view
  get "/customer_report" => "admin#customer_report", as: :customer_report
  get "/access_control" => "access#access_control", as: :access_control
  get "/update_profile_view" => "users#update_profile_view", as: :update_profile_view
  patch "/update_user" => "users#update_user", as: :update_user
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items

  def self.tot_amount(id)
    cart = Cart.find(id)
    sum = 0
    cart.cart_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :status, presence: true
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :price, presence: true
  validates :status, presence: true
  belongs_to :menu_category
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.date_range(first_date, last_date)
    all.where("date >= ? AND date <= ?", first_date, last_date)
  end

  def self.tot_amount(id)
    order = Order.find(id)
    sum = 0
    order.order_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :role, presence: true
  has_many :addresses
  has_many :orders
  has_secure_password

  def self.owners_and_clerks()
    all.where("role = ? OR role = ?", "clerk", "owner")
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_display_reports.html.erb
<%= link_to "<< Previous", (only_customer) ? customers_profile_view_path : reports_path, method: "get" ,class: "Previous" %>
<div class="Invoice-container">
    <div class="View-order-container" >
      <%= form_with(url: path, method: "get", class: "Date") do %>
        <% if only_customer %>
          <%= hidden_field_tag "id", @id%>
        <% end %>
        <div class="Date-body">
            <div class="Date-container">
              <h3 class="Date-text">From</h3>
              <%= date_field_tag 'first_date', nil, class: "Query-date", required: true, autofocus: true %>
            </div>
            <div class="Date-container">
              <h3 class="Date-text">To</h3>
              <%= date_field_tag 'last_date', nil,class: "Query-date", required: true %>
            </div>
        </div>
        <%= submit_tag "See report", class: "Mark-as-delivered-btn Date-submit-btn" %>
      <% end %>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead class = "table-head">
            <tr>
              <th scope="col">Order ID</th>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
              <th scope="col">Status</th>
              <th scope="col">Delivered At</th>
              <th scope="col"> Details </th>
            </tr>
          </thead>
          <tbody class = "table-body">
            <% orders.each do |ord| %>
              <tr>
                <th scope="row"> #<%= ord.id %> </th>
                <td> <%= ord.date %> </td>
                <td> <%= ord.time %> </td>
                <% if ord.archived_by == "customer" %>
                    <td> <p class="Cancelled-order-text"> Cancelled </p> </td>
                    <td> - </td>
                <% elsif ord.archived_by == "owner" || ord.archived_by == "clerk" %>
                    <td> <p class="Cancelled-order-text"> Cancelled by shop </p> </td>
                    <td> -</td>
                <% elsif ord.delivered_at.nil? %>
                      <td> <p class="Pending-order-text"> Pending </p> </td>
                      <td> - </td>
                <% else %>
                    <td> <p class="Delivered-order"> Delivered </p> </td>
                    <td> <%= ord.delivered_at.strftime("%Y-%m-%d  [%I:%M%p]")  %> </td>
                <% end %>
                <td> <%= link_to "View details", orders_path(id: ord.id, path: path, which_user_id: @id), class: "View-order-details-btn" %> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/admin/customer_report.html.erb
<%= render partial: "display_reports", locals: { only_customer: true, orders: @orders, path: "customer_report" } %>

app/views/admin/customers_profile_view.html.erb
<%= link_to "<< Previous", reports_path, method: "get" ,class: "Previous" %>
<div class="table-responsive" style="margin-top:30px;">
    <table class="table table-hover table-bordered">
      <thead class = "table-head">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Email</th>
          <th scope="col">Update</th>
        </tr>
      </thead>
      <tbody class = "table-body">
        <% @users.each do |user| %>
          <tr>
            <th scope="row"> #<%= user.id %> </th>
            <th scope="row"> <%= user.name %> </th>
             <th scope="row"> <%= user.phone_no %> </th>
            <th scope="row"> <%= user.email %> </th>
            <th scope="row"> <%= link_to "See Report",customer_report_path(id: user.id),class: "Mark-as-delivered-btn" %> </th>
           </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/admin/index.html.erb
<div class = "Home-page-container">
  <div class = "Home-item-block">
    <div class = "Home-item-left">
        <%= image_tag("reports-bar.png",class:"icon") %>
        <p>Reports</p>
    </div>
    <%= link_to "View Reports",reports_path,class:"Home-item-right" %>
  </div>
  <div class = "Home-item-block">
     <div class = "Home-item-left">
        <%= image_tag("add-user.png",class:"icon") %>
        <p> Create Owner / Billing Clerk</p>
     </div>
     <%= link_to "Create",new_user_path,class:"Home-item-right"%>
  </div>
  <div class = "Home-item-block">
     <div class = "Home-item-left">
        <%= image_tag("update-profile.png",class:"icon") %>
        <p>Update User Profile</p>
     </div>
     <%= link_to "Update",users_profile_path,class:"Home-item-right"%>
  </div>
</div>

app/views/admin/invoices.html.erb
<%= render partial: "display_reports", locals: {only_customer: false, orders: @orders, path: "invoices" } %>

app/views/admin/reports.html.erb
<%= link_to "<< Previous", admin_index_path, method: "get" ,class: "Previous" %>
<div class = "Home-page-container" style="margin-top:60px;">
  <div class = "Home-item-block">
    <p>Invoices</p>
    <%= link_to "Invoices",invoices_path,class:"Home-item-right" %>
  </div>
  <div class = "Home-item-block">
     <p> Customers </p>
     <%= link_to "View Customers",customers_profile_view_path ,class:"Home-item-right"%>
  </div>
</div>

app/views/admin/update_special_users_view.html.erb
<%= link_to "<< Previous", users_profile_path, method: "get" ,class: "Previous" %>
<section class = "SignIn-container Owner-previous">
  <div class = "SignIn-container-content">
      <%= form_with(url: edit_special_users_path, method: "patch") do |form| %>
          <div class = "Form-section">
              <%= form.text_field :name,
                                  value: @user.name,
                                  class:"Form-input",
                                  placeholder:"Name",
                                  autofocus: true,
                                  pattern: ".{3,}",
                                  title: "Name should have atleast 3 characters",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.text_field :phone_no,
                                  value: @user.phone_no,
                                  class:"Form-input",
                                  placeholder:"Phone number",
                                  pattern: "[0-9]{10}",
                                  title: "Phone number should be 10 digit",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.email_field :email,
                                   value: @user.email,
                                   class:"Form-input",
                                   placeholder: "Email address",
                                   required: true %>
          </div>
          <%= hidden_field_tag "id", @id %>
          <div class = "Form-section">
              <%= form.submit "Update", class:"Form-submit"  %>
          </div>
      <% end %>
  </div>
</section>

app/views/admin/users_profile.html.erb
<%= link_to "<< Previous", admin_index_path, method: "get" ,class: "Previous" %>
<div class="table-responsive" style="margin-top:30px;">
    <table class="table table-hover table-bordered">
      <thead class = "table-head">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody class = "table-body">
        <% @users.each do |user| %>
          <tr>
            <th scope="row"> #<%= user.id %> </th>
            <th scope="row"> <%= user.name %> </th>
             <th scope="row"> <%= user.phone_no %> </th>
            <th scope="row"> <%= user.email %> </th>
            <th scope="row"> <%= user.role %> </th>
            <% if user.role == "customer" %>
               <th scope="row"> - </th>
               <th scope="row"> - </th>
            <% else %>
               <% if user.email != "admin123@gmail.com" %>
                  <th scope="row"> <%= link_to "Update Profile",update_special_users_view_path(id: user.id), class: "Mark-as-delivered-btn" %> </th>
                  <th scope="row"> <%= form_with(url: "/users/#{user.id}", method: "delete") do %>
                                        <%= image_submit_tag("trash-can.png",
                                                              class: "MenuCategory-deleteIcon",
                                                              alt: "Trash Can",
                                                              data: { confirm: 'Are you sure want to delete ?' } ) %>
                                    <% end %>
                  </th>
               <% else %>
                 <th scope="row"> - </th>
                 <th scope="row"> - </th>
               <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeteria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <% if @current_user %>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if @current_user.role == "owner" %>
                  <li class="nav-item">
                     <%= link_to "Home", admin_index_path ,class: "nav-link", style:"color:white", "aria-current":"page" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Orders", customer_orders_path , class:"nav-link", style:"color:white", "aria-current":"page"%>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"  style="color:white" href="javascript:void(0)" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                    Menu's
                  </a>
                  <ul class="dropdown-menu" id="abcd" aria-labelledby="navbarDropdown">
                    <li><%= link_to "Menu Categories", menu_categories_path, class:"dropdown-item"%></li>
                    <li><%= link_to "Menu Items", menu_items_view_path(id: 0), class:"dropdown-item" %></li>
                  </ul>
                </li>
              <% else %>
                  <li class="nav-item">
                     <%= link_to "Home", users_menu_path(id: 0),class: "nav-link", style:"color:white", "aria-current":"page" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Orders", customer_orders_path , class:"nav-link", style:"color:white", "aria-current":"page"%>
                  </li>
              <% end %>
              <% if @current_user.role == "customer" || @current_user.role == "owner" %>
                  <li class="nav-item">
                    <%= link_to "Update profile", update_profile_view_path , class:"nav-link", style:"color:white", "aria-current":"page"%>
                  </li>
              <% end %>
              <div class = "User-profile">
                <h1 class="User-profile-greeting">Welcome <%= @current_user.name %> </h1>
                <li class="nav-item">
                  <%= link_to "Sign-out", destroy_session_path ,method: "delete", style:"color:white", class:"nav-link User-profile-signout" %>
                </li>
              </div>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>