config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  resources :users, :menu_categories, :menu_items, :carts, :cart_items, :orders, :order_items, :addresses
  get "/user/menu/:id" => "customers#index", as: :users_menu
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/update_menucategory_view/:id" => "menu_categories#update_view", as: :update_category_view
  get "/add_item_view/:id" => "menu_categories#add_item_view", as: :add_item_view
  get "/menuitem_view/:id" => "menu_items#render_items", as: :menu_items_view
  get "/update_menuitem_view/:id" => "menu_items#update_view", as: :update_item_view
  post "/create_menu_category" => "menu_categories#create_category", as: :create_menu_category
  put "/add_quantity/:id" => "cart_items#add_quantity", as: :add_quantity
  put "/reduct_quantity/:id" => "cart_items#reduct_quantity", as: :reduct_quantity
  delete "/delete_all_items" => "cart_items#delete_all", as: :destroy_all_items
  get "/checkout" => "cart_items#checkout", as: :checkout
  put "/update_use_address" => "addresses#update_use_address", as: :update_use_address
  post "/orders" => "orders#create", as: :create_orders
  get "/update_address_view/:id" => "addresses#update_address_view", as: :update_address_view
  get "/customer_orders" => "orders#customer_orders", as: :customer_orders
  put "/cancel_order/:id" => "orders#cancel_order", as: :cancel_order
  put "/update_pending_order" => "orders#update_pending_order", as: :mark_as_delivered
  get "/admin" => "admin#index", as: :admin_index
  get "/reports" => "admin#reports", as: :reports
  get "/users_profile" => "admin#users_profile", as: :users_profile
  get "/update_special_users_view" => "admin#update_special_users_view", as: :update_special_users_view
  patch "/edit_special_users" => "admin#edit_special_users", as: :edit_special_users
  get "/invoices" => "admin#invoices", as: :invoices
  get "/customers_profile_view" => "admin#customers_profile_view", as: :customers_profile_view
  get "/customer_report" => "admin#customer_report", as: :customer_report
  get "/access_control" => "access#access_control", as: :access_control
  get "/update_profile_view" => "users#update_profile_view", as: :update_profile_view
  patch "/update_user" => "users#update_user", as: :update_user
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items

  def self.tot_amount(id)
    cart = Cart.find(id)
    sum = 0
    cart.cart_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :status, presence: true
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :price, presence: true
  validates :status, presence: true
  belongs_to :menu_category
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.date_range(first_date, last_date)
    all.where("date >= ? AND date <= ?", first_date, last_date)
  end

  def self.tot_amount(id)
    order = Order.find(id)
    sum = 0
    order.order_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :role, presence: true
  has_many :addresses
  has_many :orders
  has_secure_password

  def self.owners_and_clerks()
    all.where("role = ? OR role = ?", "clerk", "owner")
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_owner

  def index
  end

  def reports
  end

  def users_profile
    @users = User.all.where("archived_by IS NULL")
  end

  def update_special_users_view
    @id = params[:id]
    @user = User.find(@id)
  end

  def edit_special_users
    user = User.find(params[:id])
    user.name = params[:name]
    user.phone_no = params[:phone_no]
    user.email = params[:email]
    unless user.save
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to update_special_users_view_path(id: params[:id])
    else
      redirect_to users_profile_path
    end
  end

  def invoices
    @orders = Order.all.order(id: :desc)
    unless params[:first_date].nil?
      @orders = Order.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end

  def customers_profile_view
    @users = User.all.where("role = ?", "customer")
  end

  def customer_report
    @id = params[:id]
    user = User.find(@id)
    @orders = user.orders.order(id: :desc)
    unless params[:first_date].nil?
      @orders = @orders.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :ensure_not_owner

  def index
  end
end

app/controllers/users_controller.rb
# users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in, except: [:destroy]
  before_action :ensure_owner, only: [:destroy]
  before_action :ensure_not_clerk, only: [:update_profile_view, :update_user]

  def new
    if current_user
      if current_user.role == "customer" || current_user.role == "clerk"
        redirect_to users_menu_path(id: 0)
      end
    end
  end

  def create
    user = User.new(name: params[:name],
                    phone_no: params[:phone_no],
                    email: params[:email],
                    password: params[:password],
                    role: params[:role])

    if user.save
      if (@current_user && @current_user.role == "owner")
        Cart.create!(user_id: user.id) if params[:role] == "clerk"
        redirect_to admin_index_path and return
      end
      session[:current_user_id] = user.id
      Cart.create!(user_id: user.id)
      redirect_to users_menu_path(id: 0)
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def update_profile_view
  end

  def update_user
    user = @current_user
    user.name = params[:name]
    user.phone_no = params[:phone_no]
    user.email = params[:email]
    unless user.save
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to update_profile_view_path
    else
      if @current_user.role == "owner"
        redirect_to admin_index_path
      else
        redirect_to users_menu_path(id: 0)
      end
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.email != "admin123@gmail.com"
      user.archived_by = true
      user.save!
    end
    redirect_to users_profile_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% if flash[:error] %>
  <p class = "Flash-error">
      <%= flash[:error] %>
  </p>
<% end %>
<% if @current_user && @current_user.role == "owner" %>
   <%= link_to "<< Previous", admin_index_path, method: "get" ,class: "Previous" %>
   <section class = "SignIn-container Owner-previous">
<% else %>
   <section class = "SignIn-container">
<% end %>
  <div class = "SignIn-container-content">
      <%= form_with(url: users_path) do |form| %>
          <div class = "Form-section">
              <%= form.text_field :name,
                                  class:"Form-input",
                                  placeholder:"Name",
                                  autofocus: true,
                                  pattern: ".{3,}",
                                  title: "Name should have atleast 3 characters",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.text_field :phone_no,
                                  class:"Form-input",
                                  placeholder:"Phone number",
                                  pattern: "[0-9]{10}",
                                  title: "Phone number should be 10 digit",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.email_field :email,
                                   class:"Form-input",
                                   placeholder: "Email address",
                                   required: true %>
          </div>
          <div class = "Form-section">
              <%= form.password_field :password,
                                      class:"Form-input",
                                      placeholder:"Password",
                                      pattern: ".{7,}",
                                      title: "Please lengthen your password to 7 or more characters",
                                      required: true %>
          </div>
          <% if @current_user && @current_user.role == "owner" %>
             <div class="Owner-role-signup" >
                <h3 class="MenuCategory-status-title">Role: </h3>
                <div class="Status-container">
                    <%= radio_button_tag "role", "owner" %>
                    <p class="Status-label"> Owner </p>
                </div>
                <div class="Status-container">
                    <%= radio_button_tag "role", "clerk", true %>
                    <p class="Status-label"> Clerk </p>
                </div>
             </div>
          <% else %>
             <%= hidden_field_tag 'role', 'customer' %>
          <% end %>
          <div class = "Form-section">
              <%= form.submit "Sign-up!", class:"Form-submit"  %>
          </div>
      <% end %>
      <% unless @current_user && @current_user.role == "owner" %>
        <hr class="Bottom-line">
        <div class="ExistingUser">
            <p class="ExistingUser-text">Already existing user?  </p>
            <%= link_to "Sign In", root_path, class: "ExistingUser-link", title: "Log In" %>
        </div>
      <% end %>
  </div>
</section>

app/views/users/update_profile_view.html.erb
<% if @current_user.role == "customer" %>
   <%= link_to "<< Previous", users_menu_path(id: 0), method: "get" ,class: "Previous" %>
<% else %>
   <%= link_to "<< Previous", admin_index_path, method: "get" ,class: "Previous" %>
<% end %>
<% if flash[:error] %>
  <p class = "Flash-error">
      <%= flash[:error] %>
  </p>
<% end %>
<section class = "SignIn-container Owner-previous">
  <div class = "SignIn-container-content">
      <%= form_with(url: update_user_path, method: "patch") do |form| %>
          <div class = "Form-section">
              <%= form.text_field :name,
                                  value: @current_user.name,
                                  class:"Form-input",
                                  placeholder:"Name",
                                  autofocus: true,
                                  pattern: ".{3,}",
                                  title: "Name should have atleast 3 characters",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.text_field :phone_no,
                                  value: @current_user.phone_no,
                                  class:"Form-input",
                                  placeholder:"Phone number",
                                  pattern: "[0-9]{10}",
                                  title: "Phone number should be 10 digit",
                                  required: true %>
          </div>
          <div class = "Form-section">
              <%= form.email_field :email,
                                   value: @current_user.email,
                                   class:"Form-input",
                                   placeholder: "Email address",
                                   required: true %>
          </div>
          <div class = "Form-section">
              <%= form.submit "Update", class:"Form-submit"  %>
          </div>
      <% end %>
  </div>
</section>