config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  resources :users, :menu_categories, :menu_items, :carts, :cart_items, :orders, :order_items, :addresses
  get "/user/menu/:id" => "customers#index", as: :users_menu
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/update_menucategory_view/:id" => "menu_categories#update_view", as: :update_category_view
  get "/add_item_view/:id" => "menu_categories#add_item_view", as: :add_item_view
  get "/menuitem_view/:id" => "menu_items#render_items", as: :menu_items_view
  get "/update_menuitem_view/:id" => "menu_items#update_view", as: :update_item_view
  post "/create_menu_category" => "menu_categories#create_category", as: :create_menu_category
  put "/add_quantity/:id" => "cart_items#add_quantity", as: :add_quantity
  put "/reduct_quantity/:id" => "cart_items#reduct_quantity", as: :reduct_quantity
  delete "/delete_all_items" => "cart_items#delete_all", as: :destroy_all_items
  get "/checkout" => "cart_items#checkout", as: :checkout
  put "/update_use_address" => "addresses#update_use_address", as: :update_use_address
  post "/orders" => "orders#create", as: :create_orders
  get "/update_address_view/:id" => "addresses#update_address_view", as: :update_address_view
  get "/customer_orders" => "orders#customer_orders", as: :customer_orders
  put "/cancel_order/:id" => "orders#cancel_order", as: :cancel_order
  put "/update_pending_order" => "orders#update_pending_order", as: :mark_as_delivered
  get "/admin" => "admin#index", as: :admin_index
  get "/reports" => "admin#reports", as: :reports
  get "/users_profile" => "admin#users_profile", as: :users_profile
  get "/update_special_users_view" => "admin#update_special_users_view", as: :update_special_users_view
  patch "/edit_special_users" => "admin#edit_special_users", as: :edit_special_users
  get "/invoices" => "admin#invoices", as: :invoices
  get "/customers_profile_view" => "admin#customers_profile_view", as: :customers_profile_view
  get "/customer_report" => "admin#customer_report", as: :customer_report
  get "/access_control" => "access#access_control", as: :access_control
  get "/update_profile_view" => "users#update_profile_view", as: :update_profile_view
  patch "/update_user" => "users#update_user", as: :update_user
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items

  def self.tot_amount(id)
    cart = Cart.find(id)
    sum = 0
    cart.cart_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :status, presence: true
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :price, presence: true
  validates :status, presence: true
  belongs_to :menu_category
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.date_range(first_date, last_date)
    all.where("date >= ? AND date <= ?", first_date, last_date)
  end

  def self.tot_amount(id)
    order = Order.find(id)
    sum = 0
    order.order_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :role, presence: true
  has_many :addresses
  has_many :orders
  has_secure_password

  def self.owners_and_clerks()
    all.where("role = ? OR role = ?", "clerk", "owner")
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_owner

  def index
  end

  def reports
  end

  def users_profile
    @users = User.all.where("archived_by IS NULL")
  end

  def update_special_users_view
    @id = params[:id]
    @user = User.find(@id)
  end

  def edit_special_users
    user = User.find(params[:id])
    user.name = params[:name]
    user.phone_no = params[:phone_no]
    user.email = params[:email]
    unless user.save
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to update_special_users_view_path(id: params[:id])
    else
      redirect_to users_profile_path
    end
  end

  def invoices
    @orders = Order.all.order(id: :desc)
    unless params[:first_date].nil?
      @orders = Order.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end

  def customers_profile_view
    @users = User.all.where("role = ?", "customer")
  end

  def customer_report
    @id = params[:id]
    user = User.find(@id)
    @orders = user.orders.order(id: :desc)
    unless params[:first_date].nil?
      @orders = @orders.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :ensure_not_owner

  def index
    @menu_category = MenuCategory.all
    @id = params[:id]
    if @id == "0"
      @category = MenuCategory.find_by(status: "Active")
      redirect_to users_menu_path(id: @category.id) unless @category.nil?
    else
      @category = MenuCategory.find(@id)
    end
    @menu_items = @category.menu_items unless @category.nil?
    @cart = Cart.find_by(user_id: @current_user.id)
    @cart_items = @cart.cart_items.order(:id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/index.html.erb
<% if @menu_category.empty? %>
    <div class="Display-message">
        <%= image_tag "empty-page.png", alt: "No Items Found" %>
        <h1 class="Message-text">No categories found</h1>
    </div>
<% else %>
    <div class="Main-container">
        <ul class="MenuCategory-navbar">
            <h2 class="Item-category-title"> Menu categories </h2>
            <% @menu_category.each do |category| %>
                <li class="Item-category-item">
                  <% if (category.status == "Active") %>
                    <%= link_to category.name, "/user/menu/#{category.id}", class: "Item-category-name" %>
                  <% else %>
                    <%= link_to category.name, "javascript:void(0)", class: "Inactive-category", disable: true, title: "Not available" %>
                  <% end %>
                </li>
            <% end %>
        </ul>
        <% if @menu_items.nil? %>
            <div class="User-menu">
              <%= image_tag "empty-page.png", alt: "No Items Found" %>
              <h1 class="Message-text">No Items found</h1>
            </div>
        <% else %>
            <ul class="Item-menuCategory-body-customer">
            <h1 class="MenuItem-head"> <%= @category.name %> </h1>
                <% @menu_items.each do |item| %>
                    <li class="card" style="width: 100%;">
                      <div class="card-body">
                        <div class = "card-body-left">
                            <h5 class="card-title"> <%= item.name %> </h5>
                            <p class="card-text"> &#36; <%= item.price %> </p>
                        </div>
                        <div class = "card-body-right">
                            <% if (item.status == "Active") %>
                              <%= link_to "Add to cart", cart_items_path(id: item.id), method: "post", class: "card-link" %>
                            <% else %>
                              <a class="card-unavailable-link", href="javascript:void(0)" disabled> Unavailable </a>
                            <% end %>
                        </div>
                      </div>
                    </li>
                <% end %>
            </ul>
        <% end %>
        <div class = "Cart">
          <% if (@cart_items.empty?) %>
            <div class="Empty-cart">
              <%= image_tag "empty-cart.png", alt: "Empty cart", class: "Empty-cart-image" %>
              <h1 class="Empty-cart-text">YOUR CART IS EMPTY</h1>
            </div>
          <% else %>
            <div class="Cart-head">
              <h1 class="Cart-heading-text"> Cart </h1>
              <%= link_to "Clear cart", destroy_all_items_path, method: "delete", class: "Clear-cart", data: { confirm: 'Are you sure want to clear cart ?' }  %>
            </div>
            <ul class="Cart-body">
              <% @cart_items.each do |cart_item| %>
                <li class="Cart-item">
                    <div class="Cart-up-down">
                      <h1 class="Cart-item-name"> <%= cart_item.menu_item_name %> </h1>
                      <%= form_with(url: "/cart_items/#{cart_item.id}", method: "delete") do %>
                         <%= image_submit_tag("trash-can.png",
                                              class: "MenuCategory-deleteIcon",
                                              alt: "Trash Can") %>
                     <% end %>
                    </div>
                    <div class="Cart-up-down">
                      <h3 class="Cart-item-price"> &#36; <%= (cart_item.quantity * cart_item.menu_item_price).round(2) %> </h3>
                      <div class="Quantity">
                          <%= link_to "-", reduct_quantity_path(id: cart_item.id), class: "Quantity-change", method: "put" %>
                          <h3 class="Quantity-text"> <%= cart_item.quantity %> </h3>
                          <%= link_to "+", add_quantity_path(id: cart_item.id), class: "Quantity-change", method: "put" %>
                      </div>
                    </div>
                </li>
              <% end %>
              <div class="Total-amount">
                <h2 class="Total-amount-checkout">BILL TOTAL : </h2>
                <h3 class="Total-amount-checkout"> &#36; <%= Cart.tot_amount(@cart.id) %>
              </div>
            </ul>
            <div class="Cart-footer">
              <%= link_to "Checkout", checkout_path, method: "get", class: "Order-btn" %>
            </div>
        <% end %>
      </div>
    </div>
<% end %>