config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  resources :users, :menu_categories, :menu_items, :carts, :cart_items, :orders, :order_items, :addresses
  get "/user/menu/:id" => "customers#index", as: :users_menu
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/update_menucategory_view/:id" => "menu_categories#update_view", as: :update_category_view
  get "/add_item_view/:id" => "menu_categories#add_item_view", as: :add_item_view
  get "/menuitem_view/:id" => "menu_items#render_items", as: :menu_items_view
  get "/update_menuitem_view/:id" => "menu_items#update_view", as: :update_item_view
  post "/create_menu_category" => "menu_categories#create_category", as: :create_menu_category
  put "/add_quantity/:id" => "cart_items#add_quantity", as: :add_quantity
  put "/reduct_quantity/:id" => "cart_items#reduct_quantity", as: :reduct_quantity
  delete "/delete_all_items" => "cart_items#delete_all", as: :destroy_all_items
  get "/checkout" => "cart_items#checkout", as: :checkout
  put "/update_use_address" => "addresses#update_use_address", as: :update_use_address
  post "/orders" => "orders#create", as: :create_orders
  get "/update_address_view/:id" => "addresses#update_address_view", as: :update_address_view
  get "/customer_orders" => "orders#customer_orders", as: :customer_orders
  put "/cancel_order/:id" => "orders#cancel_order", as: :cancel_order
  put "/update_pending_order" => "orders#update_pending_order", as: :mark_as_delivered
  get "/admin" => "admin#index", as: :admin_index
  get "/reports" => "admin#reports", as: :reports
  get "/users_profile" => "admin#users_profile", as: :users_profile
  get "/update_special_users_view" => "admin#update_special_users_view", as: :update_special_users_view
  patch "/edit_special_users" => "admin#edit_special_users", as: :edit_special_users
  get "/invoices" => "admin#invoices", as: :invoices
  get "/customers_profile_view" => "admin#customers_profile_view", as: :customers_profile_view
  get "/customer_report" => "admin#customer_report", as: :customer_report
  get "/access_control" => "access#access_control", as: :access_control
  get "/update_profile_view" => "users#update_profile_view", as: :update_profile_view
  patch "/update_user" => "users#update_user", as: :update_user
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items

  def self.tot_amount(id)
    cart = Cart.find(id)
    sum = 0
    cart.cart_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :status, presence: true
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :name, { presence: true, uniqueness: true }
  validates :price, presence: true
  validates :status, presence: true
  belongs_to :menu_category
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.date_range(first_date, last_date)
    all.where("date >= ? AND date <= ?", first_date, last_date)
  end

  def self.tot_amount(id)
    order = Order.find(id)
    sum = 0
    order.order_items.each do |x|
      sum += (x.quantity * x.menu_item_price).round(2)
    end
    return sum.round(2)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :role, presence: true
  has_many :addresses
  has_many :orders
  has_secure_password

  def self.owners_and_clerks()
    all.where("role = ? OR role = ?", "clerk", "owner")
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_owner

  def index
  end

  def reports
  end

  def users_profile
    @users = User.all.where("archived_by IS NULL")
  end

  def update_special_users_view
    @id = params[:id]
    @user = User.find(@id)
  end

  def edit_special_users
    user = User.find(params[:id])
    user.name = params[:name]
    user.phone_no = params[:phone_no]
    user.email = params[:email]
    unless user.save
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to update_special_users_view_path(id: params[:id])
    else
      redirect_to users_profile_path
    end
  end

  def invoices
    @orders = Order.all.order(id: :desc)
    unless params[:first_date].nil?
      @orders = Order.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end

  def customers_profile_view
    @users = User.all.where("role = ?", "customer")
  end

  def customer_report
    @id = params[:id]
    user = User.find(@id)
    @orders = user.orders.order(id: :desc)
    unless params[:first_date].nil?
      @orders = @orders.date_range(params[:first_date].to_date, params[:last_date].to_date).order(id: :desc)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :ensure_not_owner

  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_not_owner, only: [:create]
  before_action :ensure_not_user, only: [:update_pending_order]

  def create
    cart_items = Cart.find_by(user_id: @current_user.id).cart_items
    order = Order.new(date: DateTime.now().to_date,
                      time: Time.now().strftime("%I:%M%p"),
                      user_id: @current_user.id,
                      address: (@current_user.role == "clerk") ? "walk-in-customer" : @current_user.addresses.find_by(use_address: true).address,
                      phone_no: @current_user.phone_no)
    if (order.save)
      cart_items.each do |cart_item|
        order_item = OrderItem.new(order_id: order.id,
                                   menu_item_name: cart_item.menu_item_name,
                                   menu_item_price: cart_item.menu_item_price,
                                   quantity: cart_item.quantity)
        order_item.save!
      end
      cart_items.destroy_all
    else
      flash[:error] = "Unable to place order"
    end
    redirect_to users_menu_path(id: 0)
  end

  def customer_order
  end

  def cancel_order
    if (@current_user.role == "customer")
      order = @current_user.orders.find(params[:id])
    else
      order = Order.find(params[:id])
    end
    if (order.archived_by.nil?)
      order.archived_by = @current_user.role
      order.save!
    end
    redirect_to customer_orders_path
  end

  def index
    @order_detail = Order.find(params[:id])
  end

  def update_pending_order
    order = Order.find(params[:id])
    if (order.archived_by.nil? && order.delivered_at.nil?)
      order.delivered_at = DateTime.now()
      order.save!
    end
    redirect_to customer_orders_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/customer_orders.html.erb
<% if @current_user.role == "customer" && @current_user.orders.empty? %>
    <div class="Category-path">
      <%= image_tag "empty-page.png", alt: "No Items Found" %>
      <h1 class="Message-text">No orders yet</h1>
    </div>
<% else %>
  <div class="table-responsive">
      <table class="table table-hover table-bordered">
        <thead class = "table-head">
          <tr>
            <th scope="col">Order ID</th>
            <th scope="col">Date</th>
            <th scope="col">Time</th>
            <th scope="col">Status</th>
            <th scope="col">Delivered At</th>
            <th scope="col"> Details </th>
          </tr>
        </thead>
        <tbody class = "table-body">
          <% orders = (@current_user.role == "owner" || @current_user.role == "clerk") ?  Order.all.order("delivered_at DESC NULLS FIRST","archived_by DESC NULLS FIRST") : @current_user.orders.order("delivered_at DESC NULLS FIRST","archived_by DESC NULLS FIRST") %>
          <% orders.each do |ord| %>
          <tr>
            <th scope="row"> <%= ord.id %> </th>
            <td> <%= ord.date %> </td>
            <td> <%= ord.time %> </td>
            <% if ord.archived_by == "customer" %>
               <td> <p class="Cancelled-order-text"> Cancelled </p> </td>
               <td> - </td>
            <% elsif ord.archived_by == "owner" || ord.archived_by == "clerk" %>
               <td> <p class="Cancelled-order-text"> Cancelled by shop </p> </td>
               <td> -</td>
            <% elsif ord.delivered_at.nil? %>
               <% if @current_user.role == "owner" || @current_user.role == "clerk" %>
                   <td> <%= link_to "Mark as delivered",mark_as_delivered_path(id: ord.id),method: "put", class: "Mark-as-delivered-btn" %> </td>
               <% else %>
                  <td> <p class="Pending-order-text"> Pending </p> </td>
               <% end %>
               <td> <%= link_to "Cancel order", cancel_order_path(id: ord.id), method: "put",class: "Cancel-order-btn", data: { confirm: 'Are you sure want to cancel this order ?' }  %> </td>
            <% else %>
               <td> <p class="Delivered-order"> Delivered </p> </td>
               <td> <%= ord.delivered_at.strftime("%Y-%m-%d  [%l:%M %p]")  %> </td>
            <% end %>
            <td> <%= link_to "View details", orders_path(id: ord.id, path: "customer_orders"), class: "View-order-details-btn" %> </td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>
<% end %>

app/views/orders/index.html.erb
<% if(params[:path] == "invoices") %>
    <%= link_to "<< Previous", invoices_path ,class: "Previous" %>
<% elsif(params[:path] == "customer_report") %>
    <%= link_to "<< Previous", customer_report_path(id: params[:which_user_id]) ,class: "Previous" %>
<% else %>
   <%= link_to "<< Previous", customer_orders_path ,class: "Previous" %>
<% end %>
<div class="View-order-container">
  <div class="View-order-top">
    <div class="View-order-top-firstChild">
       <div class="Order">
          <h2 class="Order-id"> ORDER-ID : </h2>
          <h3 class="Order-id-text"> <%= @order_detail.id %> </h3>
       </div>
       <div class="Status-view">
          <p class="Status-view-order"> Status : </p>
          <% if @order_detail.archived_by == "customer" %>
              <p class="Cancelled-order-text"> Cancelled </p>
          <% elsif @order_detail.archived_by == "owner" || @order_detail.archived_by == "clerk" %>
              <p class="Cancelled-order-text"> Cancelled by shop </p>
          <% elsif @order_detail.delivered_at.nil? %>
              <p class="Pending-order-text"> Pending </p>
          <% else %>
              <p class="Delivered-order"> Delivered </p>
          <% end %>
       </div>
    </div>
    <% unless @order_detail.address == "walk-in-customer"%>
      <div class="Address-view">
        <h5 class="Address-view-order">Address : </h5>
        <h6 class="Address-view-order-location"> <%= @order_detail.address %> </h6>
      </div>
    <% end %>
  </div>

  <div class="table-responsive">
    <table class="table table-hover table-bordered">
      <thead class = "table-head Invoice-head">
        <tr>
          <th scope="col">ITEM</th>
          <th scope="col">QUANTITY</th>
          <th scope="col">PRICE</th>
        </tr>
      </thead>
       <tbody class = "table-body">
        <% @order_detail.order_items.each do |order_item| %>
            <tr>
              <th scope="row"> <%= order_item.menu_item_name %> </th>
              <th scope="row"> <%= order_item.quantity %> </th>
              <th scope="row"> &#36; <%= (order_item.quantity * order_item.menu_item_price).round(2) %> </th>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<div class="Total-amount">
    <h2 class="Total-amount-checkout">BILL TOTAL : </h2>
    <h3 class="Total-amount-checkout"> &#36; <%= Order.tot_amount(@order_detail.id) %>
</div>
</div>